### PR TITLE
Theme selector and dark theme

### PR DESCRIPTION
**Pull request by rurigk**
I only added a theme selector and a dark theme

Themes are loaded from a resource file

I forgot to put it as draft

### CODE REVIEW

**Comment by rurigk** [comment]
It is necessary to correct some flaws in the themes

**Comment by kanryu** [comment]
@rurigk  It's an interesting feature.
In order to introduce it, a new setting that can be returned to the main menu or the setting dialog is necessary. How did you implement it?

**Comment by rurigk** [comment]
Take the other configurations as an example
It cost me a bit to know how that system worked since there are no comments

**Comment by rurigk** [comment]
The only problem I saw when implementing it is that when you put an empty theme (Default) you lose styles of some elements

The dark theme is based on the subject of obs-studio with some small modifications
Do you have individually defined styles in the components?

**Comment by kanryu** [comment]
@rurigk In each ui file, some widgets customize their style sheets. If you change the overall display in the theme feature, you will need to be careful not to contradict it.

By the way, when I tried to build your repository, it seems that the symbol defined by Qt-5.12 called QPalette :: PlaceholderText is used. I want to guarantee that I can build with Qt-5.9 for the time being, is it possible to fix your patch?

**Comment by rurigk** [comment]
I will try to compile it in that version of qt
It will take me a while, my internet is not very fast

And for the styles, I think we can migrate the styles that are in the ui files to the themes

**Comment by rurigk** [comment]
I could not make it work in my version of Qt Creator 4.8.2 with Qt 5.9

https://bugreports.qt.io/browse/QTBUG-72555

Could you try replacing optionsdialog.ui with the version of your branch and adding a combobox called comboBoxThemeSelector with "Default" and "Dark" items?
optionsdialog

**Comment by kanryu** [comment]
I confirmed that I can build at least qt-5.11 except where I pointed out, so I accept it once. I will fix it myself later.

Thanks!

**Pull request merged**
