### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by sakkamade**
Grammar improvements of README.md and HowToBuild.md.

### CODE REVIEW

**Comment by sakkamade** [comment]
Do not merge it yet! Reviewing it once again I have noticed a great deal of errors... 
Will update it tomorrow.

**Comment by sakkamade** [comment]
README_jp.md is slightly edited version of [index.ja](https://github.com/kanryu/quickviewer/blob/master/docs/index-ja.md).

**Comment by sakkamade** [comment]
Ready to be merged.

**Comment by kanryu** [comment]
Thanks!

**Pull request merged**
